### ISSUE TITLE
Look into SSL certificates. 

### ISSUE THREAD

**Issue by benrobson** [benrobson/zander#164]
https://stackoverflow.com/questions/11804202/how-do-i-setup-a-ssl-certificate-for-an-express-js-server

**Comment by jasoryeh** [comment]
It looks like you simply pass the key and cert where you create the express
server which you can generate with letsencrypt.

**Comment by benrobson8** [comment]
I already have an SSL certificate that I obtained from my domain provider.

**Comment by benrobson8** [comment]
https://stackoverflow.com/questions/11804202/how-do-i-setup-a-ssl-certificate-for-an-express-js-server/51937957
