### ISSUE TITLE
Attempting to login to a disabled account will not render the page with the alert.

### ISSUE THREAD

**Issue by benrobson** [benrobson/zander#196]

**Comment by jasoryeh** [comment]
What is the difference between a res.render
https://github.com/benrobson/zander-web/blob/677f3c9773872783b917c0937f7687ac036dd09c/controllers/passport.js#L28
and a return done(...)
https://github.com/benrobson/zander-web/blob/677f3c9773872783b917c0937f7687ac036dd09c/controllers/passport.js#L48
...maybe this is how you can show it's disabled?
